#==================================================================================================
# CyborgAI
# CC BY-NC-ND 4.0 Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International
# github: https:#github.com/cyborg-ai-git
#==================================================================================================
[workspace]
resolver = "2"
members = [ "evo_core_time", "rust/evo_core_time_rust"]
#==================================================================================================
[workspace.package]
version = "2025.5.310440"
edition = "2024"
#==================================================================================================